sonar.projectKey=Inkwell-Notes-App
sonar.projectName=Inkwell Notes App

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/test

sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info